### ISSUE TITLE
Remove blinking cursors

### ISSUE THREAD

**Issue by ana-silva** [IPVS-AS/MBP#93] opened 2019-02-26 11:44 UTC
If the cursor is clicked somewhere in the MBP, a blinking cursor appears as if writing would be possible. This should not be the case.

**Comment by schneijan** [comment] 2019-02-26 12:17
I am unable to reproduce this. Which browser are you using and on which page does the issue occur?

**Comment by schneijan** [comment] 2019-03-05 16:50
Did the issue occur again? Otherwise I would suggest to close this one and reopen it on demand.

**Comment by hirmerpl** [comment] 2019-03-07 12:28
not reproducable

**Closed by hirmerpl** 2019-03-07 12:28 UTC
Labels: nice-to-have
