### ISSUE TITLE
Windows work only with Remote Broker

### ISSUE THREAD

**Issue by tatianegava** [IPVS-AS/MBP#351] opened 2020-07-24 16:04 UTC
If I choose local broker it does not work in Windows, I need to choose remote and include the local IP.

<img width="359" alt="Screenshot 2020-07-24 at 18 04 13" src="https://user-images.githubusercontent.com/44437898/88411365-165c5000-cdd8-11ea-9b7a-20d4151f7636.png">

**Comment by schneijan** [comment] 2020-07-24 17:45
Works for me on Windows. This highly depends on whether the MBP is able to determine the IP address of the host device on which it is running. There is not much we could do about.

**Comment by tatianegava** [comment] 2020-07-27 06:55
@schneijan is there any configuration which I can change in my computer which could help?

**Comment by schneijan** [comment] 2020-07-29 13:35
Not really, unfortunately. I just run it within my local home network and the IP address is resolved correctly. This might depend on your local setup. The resolving of the IP address happens here: https://github.com/IPVS-AS/MBP/blob/master/src/main/java/org/citopt/connde/service/NetworkService.java

You could try to execute this on your local machine and check what happens there. Let me know if you find some potential improvements :-)

**Comment by schneijan** [comment] 2020-09-02 00:50
Can we close this one? For me it is not reproducable.

**Closed** 2020-09-25 15:16 UTC
Labels: REFUSED, bug
